name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-
    - name: Build with Maven
      run: |
        mvn clean install -DskipTests
        mvn package -DskipTests -Dmaven.repo.local=./.m2/
      env:
        CI_COMMIT_SHORT_SHA: ${{ github.sha }}

sast:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Include your SAST tools here. This example uses a placeholder for SAST analysis.
    - name: Run SAST Analysis
      run: echo "Running SAST Analysis"

  push:
    needs: build
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      run: |
        cd webgoat-server
        docker build --build-arg webgoat_version=v8.1.0 --tag ${{ secrets.DOCKER_USERNAME }}/webgoat:${{ github.sha }} --tag ${{ secrets.DOCKER_USERNAME }}/webgoat:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/webgoat:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/webgoat:latest

  dast:
    needs: push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # DAST tool integration (placeholder). Replace with your DAST tool commands or integration steps.
    - name: Run DAST Analysis
      run: |
        echo "Running DAST Analysis"
        # Example: curl command to trigger DAST scan

